from scrum.views.product_backlog_create_view import ProductBacklogCreateView 
from scrum.views.product_backlog_update_view import ProductBacklogUpdateView
from scrum.views.product_backlog_delete_view import ProductBacklogDeleteView
from scrum.views.product_backlog_detail_view import ProductBacklogDetailView
from scrum.views.product_backlog_list_view import ProductBacklogListView
from scrum.views.home import home
from scrum.views.release_backlog_create_view import ReleaseBacklogCreateView 
from scrum.views.release_backlog_update_view import ReleaseBacklogUpdateView
from scrum.views.release_backlog_delete_view import ReleaseBacklogDeleteView
from scrum.views.release_backlog_detail_view import ReleaseBacklogDetailView
from scrum.views.release_backlog_list_view import ReleaseBacklogListView
from scrum.views.release_backlog_story_delete_view import (
    ReleaseBacklogStoryDeleteView
)
from scrum.views.release_backlog_assign_scrum_master_view import (
    ReleaseBacklogAssignScrumMasterView
)
from scrum.views.user_story_create_view import UserStoryCreateView
from scrum.views.user_story_delete_view import UserStoryDeleteView
from scrum.views.user_story_detail_view import UserStoryDetailView
from scrum.views.user_story_update_view import UserStoryUpdateView
from scrum.views.user_story_to_release_view import UserStoryToReleaseView
from scrum.views.user_story_to_sprint_view import UserStoryToSprintView
from scrum.views.user_story_assign_developer_view import  (
    UserStoryAssignDeveloperView
)
from scrum.views.user_story_assign_tester_view import (
    UserStoryAssignTesterView
)
from scrum.views.sprint_create_view import SprintCreateView
from scrum.views.sprint_update_view import SprintUpdateView
from scrum.views.sprint_delete_view import SprintDeleteView
from scrum.views.sprint_story_delete_view import SprintStoryDeleteView
from scrum.views.sprint_start_view import SprintStartView
from scrum.views.sprint_end_view import SprintEndView